Update runBuild.yml

diff --git a/.github/workflows/runBuild.yml b/.github/workflows/runBuild.yml
--- a/.github/workflows/runBuild.yml
+++ b/.github/workflows/runBuild.yml
@@ -30,7 +30,9 @@ jobs:
     - name: Test with Junit
       run: mvn test
     - name: Publish Test Report
-      if: success() || failure()
-      uses: scacap/action-surefire-report@v1
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+         report_paths: '**/surefire-reports/TEST-*.xml'
     - name: Build with Maven
       run: mvn -B package --file pom.xml
